### ISSUE TITLE
Mixed class itineraries show ?s and sometimes are incorrect

### ISSUE THREAD

**Issue by m16p** [dbugger/legroom#1]
First, this extension is great, thanks for writing it!

I've noticed a few funny results with mixed-class itineraries.  These happen when you select business/first as the class, but one of the flights in the itinerary is economy instead.

  Example 1:  https://www.google.com/flights/#search;f=SFO;t=SJO;d=2018-02-18;r=2018-02-22;tt=o;sc=b;a=B6;s=1 shows a "?" for the second flight.  Though if you search for just that flight (https://www.google.com/flights/#search;f=FLL;t=SJO;d=2018-02-19;r=2018-02-23;tt=o;a=B6;s=0), it shows 34".

  Example 2:  https://www.google.com/flights/#search;f=SFO;t=GUM;d=2018-02-18;r=2018-02-22;tt=o;sc=f;a=UA;c=HND;s=1;eo=e shows lie flat / recliner for the second flights in each itinerary.  However, if you click on any of the itineraries, you see that the second flight is actually in economy.

**Comment by dbugger** [comment]
Hey thanks!

I just looked into this. Good find!

To display legroom, the extension rely on legroom information that Google Flight already have when getting back search results, but were not displayed. Seems like you have found a case in which the legroom information is incomplete. The information is there when we click on the itinerary, because the page makes another server call to get that extra info.

I'll look into it some more to see if there's a smart way around it. Seems like the best course for now is to display an indicator that the flight is probably an Economy flight instead of a '?'.

**Comment by dbugger** [comment]
Closing out an old issue here.
It does not seem like this issue is still happening. Probably the multiple Google Flights UI updates resolved it.
