### ISSUE TITLE
New GF UI (November 2020)

### ISSUE THREAD

**Issue by donotblink** [dbugger/legroom#13]
Whatever Google did to flights appears to have interrupted Legroom... gah.

![Google Flights - Google Chrome 2020-11-17 00 38 45](https://user-images.githubusercontent.com/67981940/99350836-463ed000-286d-11eb-95e0-3f00593618c0.png)

**Comment by infdaze** [comment]
I think google moved flight search off its subdomain to the google.com domain. Seems it needs to look at https://www.google.com/travel/flights/*

**Comment by dbugger** [comment]
Good catch guys, @infdaze that's probably it. Will look into it.

**Comment by donotblink** [comment]
Any update here? Many thanks.

**Comment by dbugger** [comment]
Turns out what @infdaze said was not the only fix needed.
The new Flights UI also has a different HTML structure than before. There is some effort needed to figure out the new structure and then modify it for this extension.
Sorry folks, no promises on this, but hopefully I can find enough time to figure it out.

**Comment by aselwyn1** [comment]
> Turns out what @infdaze said was not the only fix needed.
> The new Flights UI also has a different HTML structure than before. There is some effort needed to figure out the new structure and then modify it for this extension.
> Sorry folks, no promises on this, but hopefully I can find enough time to figure it out.

thanks for doing this its a very useful tool :)

**Comment by dbugger** [comment]
Finally figured out a fix for the extension.
New version has been released and is currently pending Chrome Web Store review.

**Comment by donotblink** [comment]
Awesome. Thanks!!

**Comment by dbugger** [comment]
It is live. Version 1.9.1 is out and should work on latest Google Flights UI.
There are several issues with it that I will document in this repo and fix. Since the general functionality is working it might be best to release them with few minor issue so people can start using it.
If anyone encounter issues, feel free to file it here or comment on support.
